name: 'config-value-exporter'
description: ''
author: 'kanga333'
inputs:
  key:
    required: true
    description: 'Key of the value to export from the configuration.'
  file:
    required: true
    description: 'Path of the configuration file.'
  format:
    description: 'Format of the configuration file. If this value is empty, it will be determined from the file extension.'
runs:
  using: 'node12'
  main: 'dist/index.js'
