name: 'value-exporter'
description: ''
author: 'kanga333'
inputs:
  key: # change this
    required: true
    description: ''
  file:
    required: true
    description: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
